const nav = () => {
  const startDiv = document.getElementById('content');
  const navContainer = document.createElement('nav');
  navContainer.classList.add('navbar', 'navbar', 'navbar-expand-lg', 'navbar-dark', 'bg-dark');
  const navButton = document.createElement('button');
  navButton.classList.add('navbar-toggler');
  navButton.setAttribute('type', 'button');
  navButton.setAttribute('data-toggle', 'collapse');
  navButton.setAttribute('data-target', '#navbarNav');
  navButton.setAttribute('aria-controls', 'navbarNav');
  navButton.setAttribute('aria-expanded', 'false');
  navButton.setAttribute('aria-label', 'Toggle navigation');
  const spanElem = document.createElement('span');
  spanElem.classList.add('navbar-toggler-icon');
  navButton.appendChild(spanElem);
  const divList = document.createElement('div');
  divList.classList.add('collapse', 'navbar-collapse');
  //const ul = document.createElement('ul');
  // ul.classList.add('navbar-nav');
  const node = document.createElement('li');
  const homeNode = document.createTextNode('Home');
  const menuNode = document.createTextNode('Menu');
  const contactNode = document.createTextNode('Contact');
  node.appendChild(homeNode);
  node.appendChild(menuNode);
  node.appendChild(contactNode);
  document.getElementsByClassName('navbar-nav').appendChild(node).appendChild(divList);
  startDiv.appendChild(navContainer);
};